import { defineConfig, presetUno, presetTypography } from 'unocss'

// Design tokens are defined as CSS custom properties in src/styles/global.css
// (:root for light, [data-theme="dark"] for dark). UnoCSS color utilities map
// to those variables — components never use bare color values.
export default defineConfig({
  presets: [
    presetUno(),
    // Prose refinement: previously defined in src/styles/global.css (.prose
    // rules), now moved here via cssExtend so they live with the typography
    // preset. Values unchanged — visual output identical. See the not-prose
    // handling below: cssExtend selectors automatically get the :not([not-prose])
    // guard, matching the old global.css rules.
    presetTypography({
      cssExtend: {
        'max-width': '72ch',
        'h1,h2,h3,h4': {
          'scroll-margin-top': '5rem',
        },
        code: {
          'font-size': '0.9em',
          'font-weight': '600',
        },
        pre: {
          'background-color': 'var(--color-surface)',
          border: '1px solid var(--color-border)',
          'border-radius': '8px',
        },
        blockquote: {
          'border-left-color': 'var(--color-accent)',
        },
        a: {
          'text-decoration-color': 'var(--color-accent)',
          'text-underline-offset': '2px',
        },
      },
    }),
  ],
  content: {
    filesystem: ['src/**/*.{astro,md,ts,html}'],
  },
  shortcuts: {
    'container-site': 'mx-auto max-w-6xl px-6',
    'btn-primary': 'inline-flex items-center gap-2 rounded-lg bg-accent text-fg-invert px-5 py-2.5 text-sm font-medium transition-colors hover:bg-accent-strong active:bg-accent-strong/80',
    'btn-secondary': 'inline-flex items-center gap-2 rounded-lg border border-border bg-surface px-5 py-2.5 text-sm font-medium transition-colors hover:bg-surface-2 active:bg-surface-2/80',
    'card': 'rounded-xl border border-border bg-surface p-6',
  },
  theme: {
    colors: {
      // Mapped to CSS custom properties defined in global.css.
      // Using color-mix + calc so opacity modifiers (e.g. bg-bg/80) work
      // correctly. <alpha-value> is 0–1; *100 converts to percentage.
      bg: 'color-mix(in srgb, var(--color-bg) calc(<alpha-value> * 100)%, transparent)',
      surface: 'color-mix(in srgb, var(--color-surface) calc(<alpha-value> * 100)%, transparent)',
      'surface-2': 'color-mix(in srgb, var(--color-surface-2) calc(<alpha-value> * 100)%, transparent)',
      fg: 'color-mix(in srgb, var(--color-fg) calc(<alpha-value> * 100)%, transparent)',
      'fg-muted': 'color-mix(in srgb, var(--color-fg-muted) calc(<alpha-value> * 100)%, transparent)',
      'fg-invert': 'color-mix(in srgb, var(--color-fg-invert) calc(<alpha-value> * 100)%, transparent)',
      border: 'color-mix(in srgb, var(--color-border) calc(<alpha-value> * 100)%, transparent)',
      accent: 'color-mix(in srgb, var(--color-accent) calc(<alpha-value> * 100)%, transparent)',
      'accent-strong': 'color-mix(in srgb, var(--color-accent-strong) calc(<alpha-value> * 100)%, transparent)',
      'accent-soft': 'color-mix(in srgb, var(--color-accent-soft) calc(<alpha-value> * 100)%, transparent)',
      // NOTE: no custom red/amber/green keys here. CodeBlock's macOS-style
      // traffic light dots use presetUno standard palette classes
      // (bg-red-500 / bg-yellow-500 / bg-green-500) instead — guaranteed to
      // be generated by the default theme, no custom-key risk.
    },
  },
})