#!/usr/bin/env python3
"""
update_free_models.py — Refresh config/free-models.yml from the live opencode model list.

Queries `opencode models opencode --refresh`, extracts all free models
(model IDs ending in `-free`), and rewrites config/free-models.yml:

  - preserves the existing order (coding ability, strongest first)
  - removes models that are no longer available on the platform
  - appends newly discovered free models at the end of the queue
    (sorted alphabetically — we cannot auto-rank coding ability of new models)

This is the writer half of the "auto-updating fallback queue" design.
The reader half (composite action + fixture runner) consumes the same file
at runtime, so a delisted model is never retried and a new model is picked
up automatically — no manual fixes required.

Usage:
  python3 tools/update_free_models.py             # update config if changed
  python3 tools/update_free_models.py --check     # validate config only (no network)

Exit codes:
  0 — config unchanged (or --check passed)
  1 — config updated (or --check failed)
  2 — usage / runtime error
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "free-models.yml"

# Models in the queue that must stay ordered by coding ability. Used as the
# initial seed; the refresh logic preserves the order of these entries and
# appends any newly discovered free models after them.
# NOTE: opencode/deepseek-v4-flash-free is the PRIMARY model and lives in
# the `primary` field, not in this list.
BUILTIN_FALLBACK = [
    "opencode/hy3-free",
    "opencode/nemotron-3-ultra-free",
    "opencode/laguna-s-2.1-free",
    "opencode/nemotron-3.5-lightning-free",
    "opencode/mimo-v2.5-free",
]
BUILTIN_PRIMARY = "opencode/deepseek-v4-flash-free"

HEADER = """\
# Argus free model list — single source of truth for the fallback queue.
#
# Auto-generated by tools/update_free_models.py via the scheduled workflow
# .github/workflows/update-free-models.yml (runs every 12 hours).
# Do not edit manually — the workflow refreshes this file from the live
# `opencode models opencode` list.
#
# Order = coding ability, strongest first. Newly available models are
# appended at the end; models no longer available are removed.
"""


# ── Parsing helpers ──────────────────────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    """Remove ANSI escape sequences from CLI output."""
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", text)


def _parse_config(path: Path) -> dict:
    """Parse the simple `key: value` config format (zero dependencies)."""
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        data[key.strip()] = val.strip()
    return data


def _write_config(path: Path, primary: str, fallback: list[str]) -> None:
    """Write the config file with a fresh generated_at timestamp."""
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = (
        HEADER
        + f"generated_at: {now}\n"
        + f"primary: {primary}\n"
        + f"fallback_models: {','.join(fallback)}\n"
    )
    path.write_text(content, encoding="utf-8")


# ── opencode interaction ─────────────────────────────────────────────────────

def _find_opencode() -> str | None:
    """Locate the opencode CLI (PATH first, then the standard install dir)."""
    for candidate in [os.environ.get("OPENCODE_BIN", ""), "opencode",
                      str(Path.home() / ".opencode" / "bin" / "opencode")]:
        if not candidate:
            continue
        try:
            subprocess.run([candidate, "--version"], capture_output=True, timeout=10)
            return candidate
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return None


def _list_free_models(opencode: str) -> set[str]:
    """Run `opencode models opencode --refresh` and return free model IDs."""
    try:
        result = subprocess.run(
            [opencode, "models", "opencode", "--refresh"],
            capture_output=True, text=True, timeout=60,
        )
        output = _strip_ansi(result.stdout + result.stderr)
    except subprocess.TimeoutExpired:
        raise RuntimeError("`opencode models opencode --refresh` timed out (60s)")
    except Exception as exc:
        raise RuntimeError(f"Failed to run opencode models: {exc}")

    models: set[str] = set()
    for line in output.splitlines():
        # Skip lines that look like error messages to avoid false positives.
        stripped = line.strip()
        if not stripped or stripped.startswith("["):
            continue
        m = re.search(r"\bopencode/[A-Za-z0-9._-]+-free\b", line)
        if m:
            models.add(m.group(0))
    return models


# ── Core logic ───────────────────────────────────────────────────────────────

def compute_fallback(current_fallback: list[str], live_free: set[str],
                     primary: str | None = None) -> list[str]:
    """
    Reconcile the current queue against the live free-model set.

    Known models keep their existing order (coding ability, strongest first
    as human-curated). Models no longer available are dropped. Newly
    discovered free models are appended at the end in sorted order
    (alphabetical) — we cannot auto-rank the coding ability of a model
    we have not seen before.

    The primary model is never part of the fallback queue.
    """
    if primary:
        live_free = live_free - {primary}
    known = set(current_fallback)
    still_available = [m for m in current_fallback if m in live_free]
    newly_added = sorted(live_free - known)
    return still_available + newly_added


def refresh() -> int:
    """Query opencode and rewrite the config if the list changed."""
    opencode = _find_opencode()
    if opencode is None:
        print("[update-free-models] ✗ opencode CLI not found — cannot refresh", file=sys.stderr)
        return 2

    try:
        live_free = _list_free_models(opencode)
    except RuntimeError as exc:
        print(f"[update-free-models] ✗ {exc}", file=sys.stderr)
        return 2

    if not live_free:
        print("[update-free-models] ✗ No free models returned by opencode — aborting to avoid clobbering config", file=sys.stderr)
        return 2

    current = _parse_config(CONFIG_PATH)
    current_fallback = [m.strip() for m in current.get("fallback_models", "").split(",") if m.strip()] or BUILTIN_FALLBACK
    primary = current.get("primary") or BUILTIN_PRIMARY

    new_fallback = compute_fallback(current_fallback, live_free, primary)

    dropped = [m for m in current_fallback if m not in live_free]
    added = [m for m in new_fallback if m not in current_fallback]
    reordered = new_fallback != current_fallback

    if not dropped and not added and not reordered:
        print("[update-free-models] ✓ No changes — free model list is up to date")
        return 0

    _write_config(CONFIG_PATH, primary, new_fallback)

    if dropped:
        print(f"[update-free-models] − Removed delisted: {', '.join(dropped)}")
    if added:
        print(f"[update-free-models] + Added new: {', '.join(added)}")
    if reordered and not dropped and not added:
        print("[update-free-models] ↻ Order changed")
    print(f"[update-free-models] ✓ Updated {CONFIG_PATH.relative_to(REPO_ROOT)}")
    return 1


def check() -> int:
    """Validate the existing config file (no network). Used by CI."""
    if not CONFIG_PATH.exists():
        print(f"[update-free-models] ✗ {CONFIG_PATH.relative_to(REPO_ROOT)} missing", file=sys.stderr)
        return 1
    data = _parse_config(CONFIG_PATH)
    errors: list[str] = []
    primary = data.get("primary", "")
    fallback = [m.strip() for m in data.get("fallback_models", "").split(",") if m.strip()]
    if not primary:
        errors.append("missing 'primary'")
    elif not primary.startswith("opencode/") or not primary.endswith("-free"):
        errors.append(f"invalid primary model id: '{primary}'")
    if not fallback:
        errors.append("empty 'fallback_models'")
    for m in fallback:
        if not m.startswith("opencode/") or not m.endswith("-free"):
            errors.append(f"invalid free model id: '{m}'")
    if data.get("primary") in fallback:
        errors.append("primary model must not appear in fallback_models")
    if errors:
        for err in errors:
            print(f"[update-free-models] ✗ {err}", file=sys.stderr)
        return 1

    # Assert that built-in defaults match the committed config to prevent drift.
    # If the config was manually changed or the auto-refresh workflow added a
    # model without updating the built-ins, CI will catch it.
    builtin = BUILTIN_FALLBACK
    for idx, model in enumerate(builtin):
        if idx >= len(fallback) or fallback[idx] != model:
            # drift detected — warn but don't block (built-ins are last-resort
            # and the config is the source of truth)
            print(f"[update-free-models] ⚠ Built-in default #{idx} '{model}' "
                  f"differs from config '{fallback[idx] if idx < len(fallback) else '(missing)'}'",
                  file=sys.stderr)
            break
    if len(fallback) > len(builtin):
        extra = ', '.join(fallback[len(builtin):])
        print(f"[update-free-models] ⚠ Config has {len(fallback) - len(builtin)} more model(s) "
              f"than built-in defaults: {extra}", file=sys.stderr)

    # Also verify the composite action's hardcoded last-resort default queue
    # (action.yml) matches the committed config, so all three copies stay in sync.
    # Match only the literal model-list assignment (value starts with "opencode/"),
    # not the input-resolution line FALLBACK_MODELS="${{ inputs.fallback-models }}".
    action_path = REPO_ROOT / ".github" / "actions" / "argus-review" / "action.yml"
    if action_path.exists():
        text = action_path.read_text(encoding="utf-8")
        m = re.search(r'^[ \t]*FALLBACK_MODELS=["\'](opencode/[^"\']+)["\']', text, re.M)
        if not m:
            print("[update-free-models] ⚠ action.yml fallback literal not found "
                  "— drift check skipped", file=sys.stderr)
        else:
            action_fallback = [x.strip() for x in m.group(1).split(",") if x.strip()]
            if action_fallback != fallback:
                print(f"[update-free-models] ⚠ action.yml last-resort queue differs from config: "
                      f"{', '.join(action_fallback)}", file=sys.stderr)

    print(f"[update-free-models] ✓ Config valid ({len(fallback)} fallback models, primary: {primary})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh config/free-models.yml from the live opencode model list",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--check", action="store_true",
                        help="Validate the existing config file only (no network)")
    args = parser.parse_args()

    try:
        if args.check:
            return check()
        return refresh()
    except Exception as exc:
        print(f"[update-free-models] ✗ Unexpected error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
