#!/usr/bin/env python3
"""
update_free_models.py — Refresh config/free-models.yml from the live opencode model list.

Queries the public OpenCode Zen model API (GET https://opencode.ai/zen/v1/models),
extracts all free models (model IDs ending in `-free`), and rewrites
config/free-models.yml:

  - ranks all available free models by a composite coding-ability score
  - drops models that are no longer available on the platform
  - appends newly discovered free models at the end of the queue
    (sorted alphabetically — we cannot auto-rank coding ability of new models)
  - re-selects the primary model: the current primary is kept while it is
    still live; otherwise the highest-ranked live model is promoted

Model score metadata lives in config/model-scores.yml (single source of
truth for the ranking). Auto-refreshed model IDs that are not listed there
get score 0 and are placed at the bottom of the queue; they are flagged for
human review but never auto-promoted to primary.

When the API is unreachable, the script degrades to the opencode CLI
(`opencode models opencode --refresh`) if available, and aborts without
touching the config if neither source works.

This is the writer half of the "auto-updating fallback queue" design.
The reader half (composite action + fixture runner) consumes the same file
at runtime, so a delisted model is never retried and a new model is picked
up automatically — no manual fixes required.

The scheduled workflow opens a reviewable pull request (with the
`models-auto` label) instead of pushing to main directly, so a bad or
deprecated model never lands without human review.

Usage:
  python3 tools/update_free_models.py             # update config if changed
  python3 tools/update_free_models.py --check     # validate config only (no network)
  python3 tools/update_free_models.py --rank      # print ranking table (no network)
  python3 tools/update_free_models.py --dry-run   # show would-be diff, write nothing (network)
  python3 tools/update_free_models.py --inspect   # print raw API entry shape (debugging, network)

Exit codes:
  0 — config unchanged (or --check passed; --dry-run with no changes)
  1 — config updated, --dry-run shows changes, or --check failed
  2 — usage / runtime error
"""

from __future__ import annotations

import argparse
import datetime
import itertools
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

# Force UTF-8 output so non-ASCII log glyphs (↻ → −) never crash on
# Windows GBK consoles; CI runners (UTF-8) are unaffected.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "free-models.yml"
MODEL_SCORES_PATH = REPO_ROOT / "config" / "model-scores.yml"

# Public OpenCode Zen model API — no authentication required. Returns all
# models (paid + free); free models are identified by the `-free` id suffix.
FREE_MODELS_API = "https://opencode.ai/zen/v1/models"
FREE_MODEL_RE = re.compile(r"\bopencode/[A-Za-z0-9._-]+-free\b")

# ── Benchmark data ───────────────────────────────────────────────────────────
#
# Scoring methodology:
#   The primary signal is SWE-bench (Verifiable or Verified), which measures
#   real-world coding task solving — directly relevant to Argus' code-review
#   use case. Models without SWE-bench data use a fallback benchmark:
#
#     SWE-bench Verifiable / Verified  → used directly (weight 1.0)
#     SWE-bench Pro                   → scaled × 0.65 (Pro uses a different
#                                        task set with a higher human baseline)
#     Intelligence Index (0-100)      → scaled × 0.70 (general capability,
#                                        not coding-specific)
#     No coding-relevant data         → score 0 (placed at the bottom)
#
# This scoring is approximate; benchmarks are not perfectly comparable.
# However, it produces a defensible ordering for the fallback queue.
#
# The per-model score metadata (score / benchmark / source / confidence,
# plus optional regions / deprecated / capabilities) lives in
# config/model-scores.yml — see that file for the full data.
# Score weight multipliers per benchmark type (applied in composite_score()).
SCORE_WEIGHTS = {
    "swebench_verifiable": 1.0,
    "swebench_verified": 1.0,
    "swebench_pro": 0.65,
    "intelligence_index": 0.70,
    "none": 0.0,
}
# Last-known-good primary — used as a built-in fallback when the config file
# is missing or the live list cannot be fetched.
BUILTIN_PRIMARY = "opencode/deepseek-v4-flash-free"

HEADER = """\
# Argus free model list — single source of truth for the fallback queue.
#
# Auto-generated by tools/update_free_models.py via the scheduled workflow
# .github/workflows/update-free-models.yml (runs weekly; opens a reviewable PR).
# Do not edit manually — the workflow refreshes this file from the live
# OpenCode Zen model API and ranks models by coding-ability score.
#
# Scoring: SWE-bench (Verifiable/Verified) → SWE-bench Pro → Intelligence
# Index → unknown. See config/model-scores.yml for details.
"""


# ── Model score metadata loading ─────────────────────────────────────────────

_SCORES_CACHE: dict[str, dict] | None = None


def _coerce_scalar(val: str):
    """Best-effort scalar coercion for the simple model-scores parser."""
    v = val.strip().strip('"\'')
    if v in ("true", "True"):
        return True
    if v in ("false", "False"):
        return False
    if v in ("null", "None", "~"):
        return None
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        if not inner:
            return []
        return [_coerce_scalar(x) for x in inner.split(",")]
    if re.fullmatch(r"-?\d+", v):
        return int(v)
    if re.fullmatch(r"-?\d+\.\d+", v):
        return float(v)
    return v


def _parse_model_scores_simple(text: str) -> dict[str, dict]:
    """Indentation-based parser for config/model-scores.yml (fixed layout).

    Handles the exact two-level structure this repo owns:

        models:
          opencode/<id>:          # two-space indent, model id key
            key: value            # four-space indent, scalar field

    Nested list blocks (``- item`` under a ``key:`` line) and inline lists
    (``key: [a, b]``) are tolerated so optional fields like ``regions`` /
    ``capabilities`` never crash the loader. Comments and blank lines are
    skipped. This fallback exists so the tool works without PyYAML.
    """
    scores: dict[str, dict] = {}
    current_id: str | None = None
    list_key: str | None = None
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if indent == 0:
            # Top-level key (`models:` etc.) — resets the current model.
            current_id = None
            list_key = None
            continue
        if indent == 2:
            # Model id line: `  opencode/<id>:` (two-space indent).
            if stripped.endswith(":") and not stripped.startswith("- "):
                current_id = stripped[:-1].strip()
                scores.setdefault(current_id, {})
                list_key = None
            continue
        if indent == 4:
            if current_id is None:
                continue
            if ":" not in stripped:
                continue
            key, _, val = stripped.partition(":")
            key = key.strip()
            val = val.strip()
            if val:
                scores[current_id][key] = _coerce_scalar(val)
                list_key = None
            else:
                # Empty value — may be a block list start (`regions:`).
                scores[current_id][key] = []
                list_key = key
            continue
        if indent >= 6 and list_key is not None and current_id is not None:
            item = stripped
            if item.startswith("- "):
                item = item[2:].strip()
            lst = scores[current_id].get(list_key)
            if isinstance(lst, list):
                lst.append(_coerce_scalar(item))
            continue
    return scores


def _load_model_scores() -> dict[str, dict]:
    """Load model score metadata from config/model-scores.yml.

    Zero-dependency loader: uses PyYAML when available, otherwise a small
    indentation parser for the fixed two-level layout. Returns {} when the
    file is missing (callers treat that as "no score data").
    """
    global _SCORES_CACHE
    if _SCORES_CACHE is not None:
        return _SCORES_CACHE
    if not MODEL_SCORES_PATH.exists():
        print(f"[update-free-models] ⚠ {MODEL_SCORES_PATH.relative_to(REPO_ROOT)} missing "
              f"— treating as empty score set", file=sys.stderr)
        _SCORES_CACHE = {}
        return _SCORES_CACHE
    text = MODEL_SCORES_PATH.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore[import-not-found]
    except ImportError:
        _SCORES_CACHE = _parse_model_scores_simple(text)
        return _SCORES_CACHE
    try:
        data = yaml.safe_load(text)
    except Exception as exc:
        print(f"[update-free-models] ⚠ yaml.safe_load failed ({exc}) — using simple parser",
              file=sys.stderr)
        _SCORES_CACHE = _parse_model_scores_simple(text)
        return _SCORES_CACHE
    models = data.get("models", {}) if isinstance(data, dict) else {}
    _SCORES_CACHE = (
        {mid: fields for mid, fields in models.items()
         if isinstance(mid, str) and isinstance(fields, dict)}
        if isinstance(models, dict) else {}
    )
    return _SCORES_CACHE


# Compatibility export — score metadata now lives in config/model-scores.yml.
# The symbol is kept so tools/run_fixture_tests.py can keep importing the
# loaded score map without duplicating the data source.
MODEL_SCORES = _load_model_scores()


# ── Parsing helpers ──────────────────────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    """Remove ANSI escape sequences from CLI output."""
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", text)


def _parse_config(path: Path) -> dict:
    """Parse the simple `key: value` config format (zero dependencies)."""
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        data[key.strip()] = val.strip()
    return data


def _write_config(path: Path, primary: str, fallback: list[str]) -> None:
    """Write the config file with a fresh generated_at timestamp."""
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = (
        HEADER
        + f"generated_at: {now}\n"
        + f"primary: {primary}\n"
        + f"fallback_models: {','.join(fallback)}\n"
    )
    path.write_text(content, encoding="utf-8")


def composite_score(opencode_id: str) -> float:
    """
    Return a comparable 0-100 coding-ability score for the given model.

    Uses SWE-bench as the primary signal, falling back to other benchmarks
    with appropriate weight scaling. Models with no data get score 0.
    """
    entry = _load_model_scores().get(opencode_id)
    if not entry:
        return 0.0
    raw = entry.get("score", 0.0) or 0.0
    weight = SCORE_WEIGHTS.get(entry.get("benchmark", "none"), 0.0)
    return round(float(raw) * weight, 1)


def rank_models(model_ids: list[str]) -> list[str]:
    """Sort model IDs by composite score (descending), then alphabetically."""
    return sorted(model_ids, key=lambda m: (-composite_score(m), m))


def print_ranking() -> None:
    """Print a formatted ranking table of all known free models."""
    scores = _load_model_scores()
    known = list(scores.keys())
    ranked = rank_models(known)
    print(f"{'Rank':<5} {'Model':<45} {'Score':<8} {'Benchmark':<22} {'Confidence'}")
    print(f"{'─'*5} {'─'*45} {'─'*8} {'─'*22} {'─'*10}")
    for i, mid in enumerate(ranked, 1):
        entry = scores[mid]
        raw = entry.get("score", 0.0) or 0.0
        cscore = composite_score(mid)
        benchmark = entry.get("benchmark", "none")
        conf = entry.get("confidence", "none")
        print(f"{i:<5} {mid:<45} {cscore:<8.1f} {benchmark:<22} {conf}")


# ── Live model list retrieval ────────────────────────────────────────────────

def _find_opencode() -> str | None:
    """Locate the opencode CLI (PATH first, then the standard install dir).

    Uses ``shutil.which`` so Windows npm shims (``opencode.cmd``) and other
    PATHEXT-resolved executables are found, not just bare ``opencode``.
    """
    candidates = [os.environ.get("OPENCODE_BIN", ""), "opencode",
                  str(Path.home() / ".opencode" / "bin" / "opencode")]
    for candidate in candidates:
        if not candidate:
            continue
        resolved = shutil.which(candidate) if not os.path.isabs(candidate) else candidate
        if not resolved:
            continue
        try:
            subprocess.run([resolved, "--version"], capture_output=True, timeout=10)
            return resolved
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return None


def _fetch_live_entries() -> list[dict] | None:
    """Fetch raw model entries from the public OpenCode Zen API.

    Returns the parsed ``data`` list (list of dicts), or None when the API
    is unreachable. Kept separate from the free-model filtering so
    ``--inspect`` can print the raw entry shape.
    """
    try:
        # The API rejects urllib's default User-Agent (403), so send an
        # explicit UA header — same approach works in CI runners.
        req = urllib.request.Request(
            FREE_MODELS_API,
            headers={"User-Agent": "argus-update-free-models/0.4"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"[update-free-models] ⚠ Live API unreachable: {exc}", file=sys.stderr)
        return None

    data = payload.get("data", [])
    return data if isinstance(data, list) else []


def _fetch_live_free_models() -> set[str] | None:
    """Fetch the live free model list from the public OpenCode Zen API.

    Only IDs ending in ``-free`` are kept, normalized to ``opencode/<id>``
    form. Entries flagged ``deprecated`` by the API are skipped. Returns
    None when the API is unreachable so the caller can fall back to the
    opencode CLI.
    """
    entries = _fetch_live_entries()
    if entries is None:
        return None

    models: set[str] = set()
    for entry in entries:
        mid = str(entry.get("id", ""))
        # API may flag deprecated models — never put them back in the queue.
        if entry.get("deprecated"):
            print(f"[update-free-models] − Skipped deprecated (API): {mid}")
            continue
        # API returns bare IDs (e.g. `deepseek-v4-flash-free`); normalize by
        # prefixing the provider and matching the `opencode/<id>-free` pattern.
        m = FREE_MODEL_RE.search(f"opencode/{mid}")
        if m:
            models.add(m.group(0))
    return models


def _list_free_models(opencode: str) -> set[str]:
    """CLI fallback: run `opencode models opencode --refresh` and return free model IDs."""
    try:
        result = subprocess.run(
            [opencode, "models", "opencode", "--refresh"],
            capture_output=True, text=True, timeout=60,
        )
        output = _strip_ansi(result.stdout + result.stderr)
    except subprocess.TimeoutExpired:
        raise RuntimeError("`opencode models opencode --refresh` timed out (60s)")
    except Exception as exc:
        raise RuntimeError(f"Failed to run opencode models: {exc}")

    models: set[str] = set()
    for line in output.splitlines():
        # Skip empty lines. Only skip obvious log-level lines (e.g. `[error] ...`),
        # not rows that legitimately start with `[` (numbered/bracketed output).
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.lower().startswith(("[error", "[warn", "[info")):
            continue
        m = FREE_MODEL_RE.search(stripped)
        if not m:
            # The CLI may print bare IDs without the `opencode/` provider
            # prefix — retry with the prefix added to catch them.
            m = FREE_MODEL_RE.search("opencode/" + stripped)
        if m:
            models.add(m.group(0))
    return models


def inspect_api() -> int:
    """Print the raw shape of the first few API entries (debugging aid)."""
    entries = _fetch_live_entries()
    if entries is None:
        print("[update-free-models] ⚠ inspect unavailable — API unreachable", file=sys.stderr)
        return 1
    print(f"[update-free-models] API returned {len(entries)} entries; showing first 5 (debugging):")
    for i, entry in enumerate(entries[:5], 1):
        print(f"  #{i}: {json.dumps(entry, ensure_ascii=False)}")
    return 0


# ── Core logic ───────────────────────────────────────────────────────────────

def compute_fallback(live_free: set[str], primary: str | None = None) -> list[str]:
    """
    Reconcile the live free-model set into an ordered fallback queue.

    All known models (in config/model-scores.yml) are ranked by their
    composite coding ability score. Models no longer available are dropped.
    Newly discovered free models (not in model-scores.yml) are appended at
    the end in alphabetical order — we cannot auto-rank the coding ability
    of a model we have not seen before.

    The primary model is never part of the fallback queue.
    """
    if primary:
        live_free = live_free - {primary}
    scores = _load_model_scores()
    known = set(scores.keys())
    ranked_known = [m for m in rank_models(known) if m in live_free]
    unknown_live = sorted(m for m in live_free if m not in known)
    return ranked_known + unknown_live


def refresh(dry_run: bool = False) -> int:
    """Query the live opencode model list and rewrite the config if changed.

    With ``dry_run=True`` no file is written — the would-be changes are
    printed as a ``-``/``+`` diff instead. Exit codes mirror the write path:
    0 = no changes, 1 = changes (would be) applied, 2 = runtime error.
    """
    # Primary source: public OpenCode Zen model API (no CLI required).
    live_free = _fetch_live_free_models()

    # Optional degradation: fall back to the opencode CLI when the API is
    # unreachable. If neither works we cannot know the live set — abort
    # rather than clobber the last-known-good config.
    if live_free is None:
        opencode = _find_opencode()
        if opencode is None:
            print("[update-free-models] ✗ Live API unreachable and opencode CLI not found — cannot refresh",
                  file=sys.stderr)
            return 2
        try:
            live_free = _list_free_models(opencode)
        except RuntimeError as exc:
            print(f"[update-free-models] ✗ {exc}", file=sys.stderr)
            return 2

    if not live_free:
        print("[update-free-models] ✗ No free models returned — aborting to avoid clobbering config",
              file=sys.stderr)
        return 2

    # Cross-check against the runtime CLI registry when available: the Zen API
    # can list models that the installed OpenCode CLI cannot resolve (e.g. a
    # stale primary), which would fail every review with "Model not found".
    # The CLI registry is the runtime truth — drop API-only models from the
    # live set so primary re-selection and the fallback queue use only models
    # that actually run. In CI (no CLI installed) this degrades to API-only.
    opencode = _find_opencode()
    if opencode is not None:
        try:
            cli_free = _list_free_models(opencode)
        except RuntimeError as exc:
            print(f"[update-free-models] ⚠ CLI registry unavailable, skipping cross-check: {exc}",
                  file=sys.stderr)
            cli_free = set()
        if cli_free:
            api_only = sorted(live_free - cli_free)
            if api_only:
                print("[update-free-models] − API-listed but CLI-unavailable, excluded from live set:")
                for mid in api_only:
                    print(f"  - {mid}")
            live_free = live_free & cli_free

    if not live_free:
        print("[update-free-models] ✗ CLI cross-check emptied the live set — aborting to avoid clobbering config",
              file=sys.stderr)
        return 2

    scores = _load_model_scores()
    current = _parse_config(CONFIG_PATH)
    primary = current.get("primary") or BUILTIN_PRIMARY

    # Unknown new models: keep them in the queue (config integrity) but flag
    # them for human review — they are never auto-promoted to primary.
    unknown_live = sorted(m for m in live_free if m not in scores)
    for mid in unknown_live:
        print(f"[update-free-models] ⚠ New model needs review: {mid} — NOT in model-scores.yml")

    # Re-select primary: keep the current primary while it is still live;
    # otherwise promote the highest-ranked live model (composite score desc,
    # ties broken alphabetically).
    if primary not in live_free:
        new_primary = rank_models(list(live_free))[0]
        print(f"[update-free-models] ↻ Primary re-selected: {primary} → {new_primary}")
        primary = new_primary

    new_fallback = compute_fallback(live_free, primary)

    # Compare against existing config for change detection
    current_fallback = [m.strip() for m in current.get("fallback_models", "").split(",") if m.strip()]
    dropped = [m for m in current_fallback if m not in new_fallback]
    added = [m for m in new_fallback if m not in current_fallback]
    reordered = new_fallback != current_fallback
    primary_changed = current.get("primary") != primary

    if not dropped and not added and not reordered and not primary_changed:
        print("[update-free-models] ✓ No changes — free model list is up to date")
        return 0

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    new_content = (
        HEADER
        + f"generated_at: {now}\n"
        + f"primary: {primary}\n"
        + f"fallback_models: {','.join(new_fallback)}\n"
    )

    if dry_run:
        print("[update-free-models] --dry-run: would write the following changes:")
        old_lines = CONFIG_PATH.read_text(encoding="utf-8").splitlines() if CONFIG_PATH.exists() else []
        for old_line, new_line in itertools.zip_longest(old_lines, new_content.splitlines(), fillvalue=""):
            if old_line != new_line:
                if old_line:
                    print(f"- {old_line}")
                if new_line:
                    print(f"+ {new_line}")
        return 1

    _write_config(CONFIG_PATH, primary, new_fallback)

    if dropped:
        print(f"[update-free-models] − Removed delisted: {', '.join(dropped)}")
    if added:
        print(f"[update-free-models] + Added new: {', '.join(added)}")
    if reordered and not dropped and not added:
        print("[update-free-models] ↻ Order changed (re-ranked)")
    print(f"[update-free-models] ✓ Updated {CONFIG_PATH.relative_to(REPO_ROOT)}")
    return 1


def check() -> int:
    """Validate the existing config file (no network). Used by CI."""
    if not CONFIG_PATH.exists():
        print(f"[update-free-models] ✗ {CONFIG_PATH.relative_to(REPO_ROOT)} missing", file=sys.stderr)
        return 1
    # model-scores.yml is the score source of truth — its absence means the
    # repository is broken (every model would silently score 0).
    if not MODEL_SCORES_PATH.exists():
        print(f"[update-free-models] ✗ {MODEL_SCORES_PATH.relative_to(REPO_ROOT)} missing "
              f"— score metadata source of truth required", file=sys.stderr)
        return 1

    data = _parse_config(CONFIG_PATH)
    errors: list[str] = []
    primary = data.get("primary", "")
    fallback = [m.strip() for m in data.get("fallback_models", "").split(",") if m.strip()]
    if not primary:
        errors.append("missing 'primary'")
    elif not primary.startswith("opencode/") or not primary.endswith("-free"):
        errors.append(f"invalid primary model id: '{primary}'")
    if not fallback:
        errors.append("empty 'fallback_models'")
    for m in fallback:
        if not m.startswith("opencode/") or not m.endswith("-free"):
            errors.append(f"invalid free model id: '{m}'")
    if data.get("primary") in fallback:
        errors.append("primary model must not appear in fallback_models")

    scores = _load_model_scores()

    # Verify the config's fallback order matches the expected score ranking.
    # Models not in model-scores.yml get score 0 and should be at the bottom.
    expected_ranked = rank_models(list(scores.keys()))
    expected_ordered = [m for m in expected_ranked if m in fallback]
    config_known = [m for m in fallback if m in scores]
    if config_known != expected_ordered:
        errors.append(
            f"fallback order differs from score ranking "
            f"(expected: {', '.join(expected_ordered)})"
        )

    # Models marked deprecated in model-scores.yml must not be in the queue.
    for mid in fallback:
        entry = scores.get(mid, {})
        if entry.get("deprecated"):
            errors.append(
                f"model '{mid}' is marked deprecated in model-scores.yml but still in fallback_models"
            )

    if errors:
        for err in errors:
            print(f"[update-free-models] ✗ {err}", file=sys.stderr)
        return 1

    # Verify the composite action's hardcoded last-resort default queue
    # (action.yml) matches the committed config, so all copies stay in sync.
    # The action is now data-driven (reads config/free-models.yml at runtime),
    # so a missing literal is the expected state; a stale literal that differs
    # from config is a leftover and must fail.
    action_path = REPO_ROOT / ".github" / "actions" / "argus-review" / "action.yml"
    if action_path.exists():
        text = action_path.read_text(encoding="utf-8")
        m = re.search(r'^[ \t]*FALLBACK_MODELS=["\'](opencode/[^"\']+)["\']', text, re.M)
        if not m:
            print("[update-free-models] action.yml: no literal fallback queue (data-driven) — ok")
        else:
            action_fallback = [x.strip() for x in m.group(1).split(",") if x.strip()]
            if action_fallback != fallback:
                print(f"[update-free-models] ✗ action.yml last-resort queue differs from config: "
                      f"{', '.join(action_fallback)}", file=sys.stderr)
                return 1

    print(f"[update-free-models] ✓ Config valid ({len(fallback)} fallback models, primary: {primary})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh config/free-models.yml from the live opencode model list",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--check", action="store_true",
                        help="Validate the existing config file only (no network)")
    parser.add_argument("--rank", action="store_true",
                        help="Print the model ranking table (no network)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show the diff that would be written, without changing files (network)")
    parser.add_argument("--inspect", action="store_true",
                        help="Print raw API entry shape for the first 5 models (debugging, network)")
    args = parser.parse_args()

    try:
        if args.rank:
            print_ranking()
            return 0
        if args.inspect:
            return inspect_api()
        if args.check:
            return check()
        if args.dry_run:
            return refresh(dry_run=True)
        return refresh()
    except Exception as exc:
        print(f"[update-free-models] ✗ Unexpected error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())