#!/usr/bin/env python3
"""
update_free_models.py — Refresh config/free-models.yml from the live opencode model list.

Queries `opencode models opencode --refresh`, extracts all free models
(model IDs ending in `-free`), and rewrites config/free-models.yml:

  - ranks all available free models by a composite coding-ability score
  - drops models that are no longer available on the platform
  - appends newly discovered free models at the end of the queue
    (sorted alphabetically — we cannot auto-rank coding ability of new models)

This is the writer half of the "auto-updating fallback queue" design.
The reader half (composite action + fixture runner) consumes the same file
at runtime, so a delisted model is never retried and a new model is picked
up automatically — no manual fixes required.

Usage:
  python3 tools/update_free_models.py             # update config if changed
  python3 tools/update_free_models.py --check     # validate config only (no network)
  python3 tools/update_free_models.py --rank      # print ranking table (no network)

Exit codes:
  0 — config unchanged (or --check passed)
  1 — config updated (or --check failed)
  2 — usage / runtime error
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "free-models.yml"

# ── Benchmark data ───────────────────────────────────────────────────────────
#
# Scoring methodology:
#   The primary signal is SWE-bench (Verifiable or Verified), which measures
#   real-world coding task solving — directly relevant to Argus' code-review
#   use case. Models without SWE-bench data use a fallback benchmark:
#
#     SWE-bench Verifiable / Verified  → used directly (weight 1.0)
#     SWE-bench Pro                   → scaled × 0.65 (Pro uses a different
#                                        task set with a higher human baseline)
#     Intelligence Index (0-100)      → scaled × 0.70 (general capability,
#                                        not coding-specific)
#     No coding-relevant data         → score 0 (placed at the bottom)
#
# This scoring is approximate; benchmarks are not perfectly comparable.
# However, it produces a defensible ordering for the fallback queue.
MODEL_SCORES: dict[str, dict] = {
    "opencode/hy3-free": {
        "underlying": "Tencent Hy3 (295B MoE, 21B active)",
        "score": 78.0,
        "benchmark": "swebench_verifiable",
        "source": "https://flowtivity.ai/blog/hy3-open-source-cost-of-intelligence/",
        "confidence": "high",
    },
    "opencode/nemotron-3-ultra-free": {
        "underlying": "NVIDIA Nemotron 3 Ultra (550B MoE, 55B active)",
        "score": 70.7,
        "benchmark": "swebench_verified",
        "source": "https://developer.nvidia.com/blog/nvidia-nemotron-3-ultra-powers-faster-more-efficient-reasoning-for-long-running-agents/",
        "confidence": "high",
    },
    "opencode/muse-spark-1.2-contributor-free": {
        "underlying": "Meta Muse Spark 1.2 (Superintelligence Labs)",
        "score": 54.0,
        "benchmark": "intelligence_index",
        "source": "https://artificialanalysis.ai/articles/muse-spark-1-2",
        "confidence": "medium",
    },
    "opencode/nemotron-3.5-lightning-free": {
        "underlying": "NVIDIA Nemotron 3.5 Lightning (30B MoE, 3B active)",
        "score": 51.6,
        "benchmark": "swebench_verifiable",
        "source": "https://anotherwrapper.com/tools/llm-pricing/deepseek-v3-0324/nemotron-3.5-lightning-30b-a3b",
        "confidence": "high",
    },
    "opencode/mimo-v2.5-free": {
        "underlying": "Xiaomi MiMo-V2.5 (1.02T MoE, 42B active)",
        "score": 56.1,
        "benchmark": "swebench_pro",
        "source": "https://www.gradually.ai/en/open-source-llms/",
        "confidence": "low",
    },
    "opencode/x-preview-f-free": {
        "underlying": "xAI Grok (version unknown)",
        "score": 0.0,
        "benchmark": "none",
        "source": "https://models.opencode.ai/models/xai/grok-4.5/",
        "confidence": "none",
    },
}
# Score weight multipliers per benchmark type (applied in composite_score()).
SCORE_WEIGHTS = {
    "swebench_verifiable": 1.0,
    "swebench_verified": 1.0,
    "swebench_pro": 0.65,
    "intelligence_index": 0.70,
    "none": 0.0,
}
BUILTIN_PRIMARY = "opencode/hy3-free"

HEADER = """\
# Argus free model list — single source of truth for the fallback queue.
#
# Auto-generated by tools/update_free_models.py via the scheduled workflow
# .github/workflows/update-free-models.yml (runs every 12 hours).
# Do not edit manually — the workflow refreshes this file from the live
# `opencode models opencode` list and ranks models by coding-ability score.
#
# Scoring: SWE-bench (Verifiable/Verified) → SWE-bench Pro → Intelligence
# Index → unknown. See tools/update_free_models.py MODEL_SCORES for details.
"""


# ── Parsing helpers ──────────────────────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    """Remove ANSI escape sequences from CLI output."""
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", text)


def _parse_config(path: Path) -> dict:
    """Parse the simple `key: value` config format (zero dependencies)."""
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        data[key.strip()] = val.strip()
    return data


def _write_config(path: Path, primary: str, fallback: list[str]) -> None:
    """Write the config file with a fresh generated_at timestamp."""
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = (
        HEADER
        + f"generated_at: {now}\n"
        + f"primary: {primary}\n"
        + f"fallback_models: {','.join(fallback)}\n"
    )
    path.write_text(content, encoding="utf-8")


def composite_score(opencode_id: str) -> float:
    """
    Return a comparable 0-100 coding-ability score for the given model.

    Uses SWE-bench as the primary signal, falling back to other benchmarks
    with appropriate weight scaling. Models with no data get score 0.
    """
    entry = MODEL_SCORES.get(opencode_id)
    if not entry:
        return 0.0
    raw = entry.get("score", 0.0) or 0.0
    weight = SCORE_WEIGHTS.get(entry.get("benchmark", "none"), 0.0)
    return round(raw * weight, 1)


def rank_models(model_ids: list[str]) -> list[str]:
    """Sort model IDs by composite score (descending), then alphabetically."""
    return sorted(model_ids, key=lambda m: (-composite_score(m), m))


def print_ranking() -> None:
    """Print a formatted ranking table of all known free models."""
    known = list(MODEL_SCORES.keys())
    ranked = rank_models(known)
    print(f"{'Rank':<5} {'Model':<45} {'Score':<8} {'Benchmark':<22} {'Confidence'}")
    print(f"{'─'*5} {'─'*45} {'─'*8} {'─'*22} {'─'*10}")
    for i, mid in enumerate(ranked, 1):
        entry = MODEL_SCORES[mid]
        raw = entry.get("score", 0.0) or 0.0
        cscore = composite_score(mid)
        benchmark = entry.get("benchmark", "none")
        conf = entry.get("confidence", "none")
        print(f"{i:<5} {mid:<45} {cscore:<8.1f} {benchmark:<22} {conf}")


# ── opencode interaction ─────────────────────────────────────────────────────

def _find_opencode() -> str | None:
    """Locate the opencode CLI (PATH first, then the standard install dir)."""
    for candidate in [os.environ.get("OPENCODE_BIN", ""), "opencode",
                      str(Path.home() / ".opencode" / "bin" / "opencode")]:
        if not candidate:
            continue
        try:
            subprocess.run([candidate, "--version"], capture_output=True, timeout=10)
            return candidate
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return None


def _list_free_models(opencode: str) -> set[str]:
    """Run `opencode models opencode --refresh` and return free model IDs."""
    try:
        result = subprocess.run(
            [opencode, "models", "opencode", "--refresh"],
            capture_output=True, text=True, timeout=60,
        )
        output = _strip_ansi(result.stdout + result.stderr)
    except subprocess.TimeoutExpired:
        raise RuntimeError("`opencode models opencode --refresh` timed out (60s)")
    except Exception as exc:
        raise RuntimeError(f"Failed to run opencode models: {exc}")

    models: set[str] = set()
    for line in output.splitlines():
        # Skip lines that look like error messages to avoid false positives.
        stripped = line.strip()
        if not stripped or stripped.startswith("["):
            continue
        m = re.search(r"\bopencode/[A-Za-z0-9._-]+-free\b", line)
        if m:
            models.add(m.group(0))
    return models


# ── Core logic ───────────────────────────────────────────────────────────────

def compute_fallback(current_fallback: list[str], live_free: set[str],
                     primary: str | None = None) -> list[str]:
    """
    Reconcile the current queue against the live free-model set.

    All known models (in MODEL_SCORES) are ranked by their composite coding
    ability score. Models no longer available are dropped. Newly discovered
    free models (not in MODEL_SCORES) are appended at the end in alphabetical
    order — we cannot auto-rank the coding ability of a model we have not
    seen before.

    The primary model is never part of the fallback queue.
    """
    if primary:
        live_free = live_free - {primary}
    known = set(MODEL_SCORES.keys())
    ranked_known = [m for m in rank_models(known) if m in live_free]
    unknown_live = sorted(m for m in live_free if m not in known)
    return ranked_known + unknown_live


def refresh() -> int:
    """Query opencode and rewrite the config if the list changed."""
    opencode = _find_opencode()
    if opencode is None:
        print("[update-free-models] ✗ opencode CLI not found — cannot refresh", file=sys.stderr)
        return 2

    try:
        live_free = _list_free_models(opencode)
    except RuntimeError as exc:
        print(f"[update-free-models] ✗ {exc}", file=sys.stderr)
        return 2

    if not live_free:
        print("[update-free-models] ✗ No free models returned by opencode — aborting to avoid clobbering config", file=sys.stderr)
        return 2

    current = _parse_config(CONFIG_PATH)
    primary = current.get("primary") or BUILTIN_PRIMARY

    new_fallback = compute_fallback([], live_free, primary)

    # Compare against existing config for change detection
    current_fallback = [m.strip() for m in current.get("fallback_models", "").split(",") if m.strip()]
    dropped = [m for m in current_fallback if m not in new_fallback]
    added = [m for m in new_fallback if m not in current_fallback]
    reordered = new_fallback != current_fallback

    if not dropped and not added and not reordered:
        print("[update-free-models] ✓ No changes — free model list is up to date")
        return 0

    _write_config(CONFIG_PATH, primary, new_fallback)

    if dropped:
        print(f"[update-free-models] − Removed delisted: {', '.join(dropped)}")
    if added:
        print(f"[update-free-models] + Added new: {', '.join(added)}")
    if reordered and not dropped and not added:
        print("[update-free-models] ↻ Order changed (re-ranked)")
    print(f"[update-free-models] ✓ Updated {CONFIG_PATH.relative_to(REPO_ROOT)}")
    return 1


def check() -> int:
    """Validate the existing config file (no network). Used by CI."""
    if not CONFIG_PATH.exists():
        print(f"[update-free-models] ✗ {CONFIG_PATH.relative_to(REPO_ROOT)} missing", file=sys.stderr)
        return 1
    data = _parse_config(CONFIG_PATH)
    errors: list[str] = []
    primary = data.get("primary", "")
    fallback = [m.strip() for m in data.get("fallback_models", "").split(",") if m.strip()]
    if not primary:
        errors.append("missing 'primary'")
    elif not primary.startswith("opencode/") or not primary.endswith("-free"):
        errors.append(f"invalid primary model id: '{primary}'")
    if not fallback:
        errors.append("empty 'fallback_models'")
    for m in fallback:
        if not m.startswith("opencode/") or not m.endswith("-free"):
            errors.append(f"invalid free model id: '{m}'")
    if data.get("primary") in fallback:
        errors.append("primary model must not appear in fallback_models")
    if errors:
        for err in errors:
            print(f"[update-free-models] ✗ {err}", file=sys.stderr)
        return 1

    # Verify the config's fallback order matches the expected score ranking.
    # Models not in MODEL_SCORES get score 0 and should be at the bottom.
    expected_ranked = rank_models(list(MODEL_SCORES.keys()))
    expected_ordered = [m for m in expected_ranked if m in fallback]
    config_known = [m for m in fallback if m in MODEL_SCORES]
    if config_known != expected_ordered:
        print(f"[update-free-models] ⚠ Config order may be suboptimal "
              f"(score-ranking expected: {', '.join(expected_ordered)})",
              file=sys.stderr)

    # Also verify the composite action's hardcoded last-resort default queue
    # (action.yml) matches the committed config, so all three copies stay in sync.
    # Match only the literal model-list assignment (value starts with "opencode/"),
    # not the input-resolution line FALLBACK_MODELS="${{ inputs.fallback-models }}".
    action_path = REPO_ROOT / ".github" / "actions" / "argus-review" / "action.yml"
    if action_path.exists():
        text = action_path.read_text(encoding="utf-8")
        m = re.search(r'^[ \t]*FALLBACK_MODELS=["\'](opencode/[^"\']+)["\']', text, re.M)
        if not m:
            print("[update-free-models] ⚠ action.yml fallback literal not found "
                  "— drift check skipped", file=sys.stderr)
        else:
            action_fallback = [x.strip() for x in m.group(1).split(",") if x.strip()]
            if action_fallback != fallback:
                print(f"[update-free-models] ⚠ action.yml last-resort queue differs from config: "
                      f"{', '.join(action_fallback)}", file=sys.stderr)

    print(f"[update-free-models] ✓ Config valid ({len(fallback)} fallback models, primary: {primary})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh config/free-models.yml from the live opencode model list",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--check", action="store_true",
                        help="Validate the existing config file only (no network)")
    parser.add_argument("--rank", action="store_true",
                        help="Print the model ranking table (no network)")
    args = parser.parse_args()

    try:
        if args.rank:
            print_ranking()
            return 0
        if args.check:
            return check()
        return refresh()
    except Exception as exc:
        print(f"[update-free-models] ✗ Unexpected error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
